language: node_js
node_js:
  - '8.9.4'
before_install:
  - openssl aes-256-cbc -K $encrypted_31a068f12a2e_key -iv $encrypted_31a068f12a2e_iv
    -in aliyun_liuxsen.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 101.200.48.138\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
  - npm run test
after_success:
  - scp README.md liuxsen@101.200.48.138:~/ # 复制到生产服务器上
  - ssh liuxsen@101.200.48.138 'mkdir -p test'
